spring.application.name=portfolio-backend

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


cloudinary.cloud-name=dy93czbmp
cloudinary.api-key=791931797979296
cloudinary.api-secret=IdViG7Gw3NRJFrXxOd9XWYBrkAQ